import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Nav from "../src/components/Navbar";
import AuthorCard from "../src/components/AuthorCard";
import Highlights from "../src/components/Highlights";
import { Center, Grid, GridItem, Box, Flex } from "@chakra-ui/react";
const Home: NextPage = () => {
  return (
    <main>
      <Head>
        <title>Personal page of Gilberto</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav></Nav>
      <AuthorCard></AuthorCard>
      <Highlights></Highlights>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </main>
  );
};

export default Home;
